/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lote } from './lote';
import { Usuario } from './usuario';
import { MedicamentosCaso } from './medicamentosCaso';


export interface AplicacionesMedicamento { 
    idAplicacionMedicamento?: number;
    idMedicamentosCaso?: number;
    idLote?: number;
    fechaHoraAplicacion?: string;
    idUsuario?: number;
    idLoteNavigation?: Lote;
    idMedicamentosCasoNavigation?: MedicamentosCaso;
    idUsuarioNavigation?: Usuario;
}

