/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductosFactura } from './productosFactura';
import { Venta } from './venta';


export interface Factura { 
    idFactura?: number;
    totalFactura?: number;
    fechaFactura?: string;
    estado?: string | null;
    productosFacturas?: Array<ProductosFactura> | null;
    venta?: Array<Venta> | null;
}

