/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AplicacionesMedicamento } from './aplicacionesMedicamento';
import { Usuario } from './usuario';
import { Producto } from './producto';


export interface MedicamentosCaso { 
    idMedicamentosCaso?: number;
    idUsuario?: number;
    idProducto?: number;
    fechaInicio?: string;
    fechaFin?: string;
    frecuencia?: number;
    dosis?: number;
    unidadMedida?: string | null;
    observaciones?: string | null;
    idProductoNavigation?: Producto;
    idUsuarioNavigation?: Usuario;
    aplicacionesMedicamentos?: Array<AplicacionesMedicamento> | null;
}

