/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lote } from './lote';
import { Producto } from './producto';
import { Factura } from './factura';


export interface ProductosFactura { 
    idProductoFactura?: number;
    idProducto?: number;
    idFactura?: number;
    idLote?: number;
    cantidad?: number;
    precioUnitario?: number;
    idFacturaNavigation?: Factura;
    idLoteNavigation?: Lote;
    idProductoNavigation?: Producto;
}

