/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TiposVentum } from './tiposVentum';
import { Usuario } from './usuario';
import { Factura } from './factura';
import { Cliente } from './cliente';


export interface Venta { 
    idVenta?: number;
    idFactura?: number;
    idCliente?: number;
    usuarioVenta?: number;
    idTipoVenta?: number;
    total?: number;
    estado?: string | null;
    fechaVenta?: string;
    idClienteNavigation?: Cliente;
    idFacturaNavigation?: Factura;
    idTipoVentaNavigation?: TiposVentum;
    usuarioVentaNavigation?: Usuario;
}

